PRAGMA foreign_keys = ON;

INSERT INTO tourguides(id, firstname, lastname, email, phone, photofile, majorone, college, city, state, rate, econe, ectwo, ecthree, currentgrade, postgradplan, aboutme, tourdescription)
VALUES (1, 'Colin', 'Brosnan', 'cbrosnan@umich.edu', 4405672000, 'Colin.jpeg', "Computer Science", "Literature, Science, and the Arts","Cleveland", "OH", 30, "Business Clubs", "Greek Life (social)", "Intramural/Recreational Sports", "Senior", "I will be working in consulting after graduation", "I am a senior at Michigan studying computer science. Originally from Cleveland, OH, I am involved with a variety of business and social clubs on campus. I am also an avid Michigan sports fan.", "we will do a tour");
INSERT INTO tourguides(id, firstname, lastname, email, phone, photofile, majorone, college, city, state, rate, econe, ectwo, ecthree, currentgrade, postgradplan, aboutme, tourdescription)
VALUES (2, 'James', 'Spillmann', 'jjspill@umich.edu', 1234567890, 'james.jpeg', "Computer Science", "Engineering", "Boulder", "CO", 45, "Art/Museum Clubs", "Musical Clubs", "Mission Trips", "Junior", "plan", "I am a junior at Michigan studying computer science. Originally from Boulder, CO, I am involved with a variety of business and social clubs on campus. I am interested in reselling and video games.", "we will do a tour");
INSERT INTO tourguides(id, firstname, lastname, email, phone, photofile, majorone, college, city, state, rate, econe, ectwo, ecthree, currentgrade, postgradplan, aboutme, tourdescription)
VALUES (3, 'Rohan', 'Saha', 'rohansa@umich.edu', 1234567890, 'rohan.jpeg', "Art & Design", "Art & Design","Alamo", "CA", 45, "Religious Club", "Activism/Social Justice Clubs", "Greek Life (professional)", "Sophomore", "plan", "I am a Sophomore at Michigan studying Art & Design. Originally from Alamo, CA, I am involved with a variety of business and social clubs on campus. I am interested in Black Ops 2 Zombies.", "we will do a tour");
INSERT INTO tourguides(id, firstname, lastname, email, phone, photofile, majorone, college, city, state, rate, econe, ectwo, ecthree, currentgrade, postgradplan, aboutme, tourdescription)
VALUES (4, 'Nick', 'Sella', 'nsella@umich.edu', 1234567890, 'sella.jpeg', "Business", "Business", "Ann Arbor", "MI", 45, "Wilderness Trips", "Business Clubs", "Greek Life (social)", "Junior", "plan", "I am a junior at Michigan studying business. Originally from Ann Arbor, MI, I am involved with a variety of business and social clubs on campus. I am interested in consulting and finance.", "we will do a tour");

INSERT INTO tourguides(id, firstname, lastname, email, phone, photofile, majorone, college, city, state, rate, econe, ectwo, ecthree, currentgrade, postgradplan, aboutme, tourdescription)
VALUES (5, 'Lily', 'Scrafano', 'lscraf@umich.edu', 1234567890, 'lily.jpeg', "Education", "Education", "Ann Arbor", "MI", 60, "Community Service Clubs", "Musical Clubs", "Dance/Theater Clubs", "Senior", "plan", "I am a senior at Michigan studying Education. Originally from Rochester, MI, I am involved with a variety of business and social clubs on campus. I am interested in Education Consulting.", "we will do a tour");

INSERT INTO tourguides(id, firstname, lastname, email, phone, photofile, majorone, college, city, state, rate, econe, ectwo, ecthree, currentgrade, postgradplan, aboutme, tourdescription)
VALUES (6, 'Fatima', 'Ali', 'fatima@umich.edu', 1234567890, 'fatima.jpeg', "Information Analysis", "Information", "Ann Arbor", "MI", 60, "Community Service Clubs", "Musical Clubs", "Dance/Theater Clubs", "Freshman", "plan", "I am a freshman at Michigan studying Information Analysis through SI. Originally from Austin, TX, I am involved with a variety of coding and design clubs. I am interested in SWE and UI/UX.", "we will do a tour");

INSERT INTO tourguides(id, firstname, lastname, email, phone, photofile, majorone, college, city, state, rate, econe, ectwo, ecthree, currentgrade, postgradplan, aboutme, tourdescription)
VALUES (7, 'Ryan', 'Breen', 'ryguy@umich.edu', 1234567890, 'ryan.jpeg', "Movement Science", "Kinesiology", "Boston", "MA", 50, "Business Clubs", "Musical Clubs", "Greek Life (social)", "Senior", "plan", "I am a senior at Michigan studying Movement Science through Kinesiology. Originally from Bostom, MA, I am involved with a variety science clubs. I am interested in medicine and game design.", "we will do a tour");

INSERT INTO tourguides(id, firstname, lastname, email, phone, photofile, majorone, college, city, state, rate, econe, ectwo, ecthree, currentgrade, postgradplan, aboutme, tourdescription)
VALUES (8, 'Charlette', 'Mitchell', 'cmitch@umich.edu', 1234567890, 'char.jpeg', "Acting", "Music, Theatre & Dance", "Postville", "IA", 50, "Business Clubs", "Musical Clubs", "Greek Life (professional)", "Junior", "plan", "I am a junior at Michigan studying acting and drama through SMTD. Originally from Postville, IA, I am involved with a variety of theater and performance clubs. I am interested in acting and modeling.", "we will do a tour");

INSERT INTO tourguides(id, firstname, lastname, email, phone, photofile, majorone, college, city, state, rate, econe, ectwo, ecthree, currentgrade, postgradplan, aboutme, tourdescription)
VALUES (9, 'Yaqub', 'Johnson', 'yjboy@umich.edu', 1234567890, 'yaqub.jpeg', "Environmental Science", "Environment and Sustainability", "Bloomfield Hills", "MI", 45, "Business Clubs", "Musical Clubs", "Greek Life (professional)", "Junior", "plan", "I am a junior at Michigan studying Environmenal Science. Originally from Bloomfield Hills, MI, I am involved in research and clubs on campus. I am interested in a career in research", "we will do a tour");

INSERT INTO tourguides(id, firstname, lastname, email, phone, photofile, majorone, college, city, state, rate, econe, ectwo, ecthree, currentgrade, postgradplan, aboutme, tourdescription)
VALUES (10, 'Caroline', 'Stice', 'sticey@umich.edu', 1234567890, 'sticey.jpeg', "Social Work", "Social Work", "Rochester Hills", "MI", 50, "Business Clubs", "Musical Clubs", "Greek Life (professional)", "Sophomore", "plan", "I am a sophomore at Michigan studying Social Work. Originally from Rochester Hills, MI, I am involved in the pre-law society on campus. I am interested in a career in law.", "we will do a tour");

INSERT INTO tourguides(id, firstname, lastname, email, phone, photofile, majorone, college, city, state, rate, econe, ectwo, ecthree, currentgrade, postgradplan, aboutme, tourdescription)
VALUES (11, 'Colleen', 'Anderson', 'coldawg@umich.edu', 1234567890, 'colleen.jpeg', "Architecture", "Architecture & Urban Planning", "Rochester Hills", "MI", 50, "Business Clubs", "Musical Clubs", "Greek Life (professional)", "Junior", "plan", "I am a junior at Michigan studying Architecture. Originally from Rochester Hills, MI, I am involved in the design society on campus. I am interested in residential architecture.", "we will do a tour");

INSERT INTO tourguides(id, firstname, lastname, email, phone, photofile, majorone, college, city, state, rate, econe, ectwo, ecthree, currentgrade, postgradplan, aboutme, tourdescription)
VALUES (12, 'Mark', 'Kava', 'markymark@umich.edu', 1234567890, 'mark.jpeg', "Public Policy", "Public Policy", "Weston", "FL", 50, "Business Clubs", "Musical Clubs", "Greek Life (social)", "Senior", "plan", "I am a senior at Michigan studying Public Policy. Originally from Weston, FL, I am involved in the pre-law society on campus. I am interested in law school and a career in big law.", "we will do a tour");

INSERT INTO tourguides(id, firstname, lastname, email, phone, photofile, majorone, college, city, state, rate, econe, ectwo, ecthree, currentgrade, postgradplan, aboutme, tourdescription)
VALUES (13, 'Jill', 'Ward', 'jwardina@umich.edu', 1234567890, 'jill.jpeg', "Nursing", "Nursing", "Traverse City", "MI", 50, "Business Clubs", "Musical Clubs", "Greek Life (professional)", "Junior", "plan", "I am a junior at Michigan studying Nursing. Originally from Traverse City, MI, I am involved in the nursing fraternity on campus. I am interested in trauma nursing.", "we will do a tour");

INSERT INTO students(username, firstname, lastname, email, phonenumber, password)
VALUES ('cbrosnan', 'colin', 'brosnan', 'cbrosnan@umich.edu', 4405672000, 'sha512$a45ffdcc71884853a2cba9e6bc55e812$c739cef1aec45c6e345c8463136dc1ae2fe19963106cf748baf87c7102937aa96928aa1db7fe1d8da6bd343428ff3167f4500c8a61095fb771957b4367868fb8' );
